# Generated by Django 4.2.17 on 2025-02-25 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("keyword", models.CharField(max_length=255, verbose_name="알림 키워드")),
                ("content", models.TextField(verbose_name="알림 내용")),
                ("is_read", models.BooleanField(default=False, verbose_name="읽음 여부")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="알림 생성 날짜"),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="읽은 날짜"),
                ),
                (
                    "contents_type",
                    models.CharField(max_length=50, verbose_name="원본 게시물 유형"),
                ),
                ("contents_id", models.IntegerField(verbose_name="원본 게시물 ID")),
                ("contents", models.TextField(verbose_name="원본 게시물 내용")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="알림을 받은 사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "알림",
                "verbose_name_plural": "알림들",
                "db_table": "notifications",
            },
        ),
    ]
