# Generated by Django 4.2.17 on 2025-07-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifs', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('like_comment', '댓글 좋아요'), ('like_reply', '대댓글 좋아요'), ('comment_note', '노트 댓글'), ('comment_pli', '플리 댓글'), ('reply_note', '노트 대댓글'), ('reply_pli', '플리 대댓글'), ('emotion', '감정 남김'), ('achievement', '칭호 획득')], max_length=20),
        ),
    ]
