# Generated by Django 4.2.17 on 2025-09-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifs', '0003_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='읽음 여부'),
        ),
    ]
