# Generated by Django 4.2.17 on 2025-09-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifs', '0004_activity_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(blank=True, choices=[('follow', '팔로우'), ('note_save', '내 노트 저장'), ('pli_save', '내 플리 저장'), ('emotion', '내 노트 감정'), ('comment', '댓글'), ('reply', '대댓글'), ('like_comment', '댓글 좋아요'), ('like_reply', '대댓글 좋아요')], max_length=20, null=True),
        ),
    ]
