# Generated by Django 4.2.17 on 2025-01-14 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='칭호 이름')),
                ('condition', models.TextField(verbose_name='칭호 조건')),
                ('emoji', models.IntegerField(default=0, verbose_name='칭호 이모지')),
            ],
            options={
                'verbose_name': '칭호',
                'verbose_name_plural': '칭호',
                'db_table': 'titles',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_hash',
        ),
        migrations.RemoveField(
            model_name='user',
            name='required_consent_date',
        ),
        migrations.AddField(
            model_name='user',
            name='required_consent',
            field=models.BooleanField(default=False, verbose_name='필수 약관 동의 여부'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.IntegerField(default=0, verbose_name='프로필'),
        ),
        migrations.CreateModel(
            name='UserTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='활성화 여부')),
                ('acquired_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='획득 날짜')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_titles', to='accounts.title', verbose_name='칭호')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_titles', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '유저 획득 칭호',
                'verbose_name_plural': '유저 획득 칭호',
                'db_table': 'user_titles',
                'unique_together': {('user', 'title')},
            },
        ),
    ]
