# Generated by Django 4.2.17 on 2025-03-07 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_title_remove_user_password_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_provider_id',
        ),
    ]
