# Generated by Django 4.2.17 on 2025-03-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_auth_provider_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='serviceID',
            field=models.CharField(default='manager', max_length=150, unique=True, verbose_name='서비스 내 아이디'),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('apple', 'Apple'), ('kakao', 'Kakao'), ('google', 'Google'), ('email', 'Email')], default='email', max_length=50),
        ),
    ]
