# Generated by Django 4.2.17 on 2025-03-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_serviceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='serviceID',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='서비스 내 아이디'),
        ),
    ]
