# Generated by Django 4.2.17 on 2025-03-21 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_serviceid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertitle',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='userdeletion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletions', to=settings.AUTH_USER_MODEL, verbose_name='탈퇴한 사용자'),
        ),
    ]
