# Generated by Django 4.2.17 on 2025-07-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_title_remove_usertitle_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='title',
        ),
        migrations.RemoveField(
            model_name='usertitle',
            name='is_active',
        ),
    ]
