# Generated by Django 4.2.17 on 2025-07-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_title_remove_usertitle_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='이메일 주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='프로필'),
        ),
    ]
