# Generated by Django 4.2.17 on 2025-07-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_email_alter_user_nickname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='title',
        ),
        migrations.RemoveField(
            model_name='usertitle',
            name='is_active',
        ),
    ]
