# Generated by Django 4.2.17 on 2025-07-19 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_email_alter_user_nickname_and_more'),
        ('accounts', '0009_remove_user_title_remove_usertitle_is_active_and_more'),
    ]

    operations = [
    ]
