# Generated by Django 4.2.17 on 2025-09-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_verifyemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='userdeletion',
            name='reason',
        ),
        migrations.AddField(
            model_name='userdeletion',
            name='reason',
            field=models.ManyToManyField(to='accounts.withdrawalreason'),
        ),
    ]
