# Generated by Django 4.2.17 on 2025-09-20 07:48

import accounts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_withdrawalreason_remove_userdeletion_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyemail',
            name='code',
            field=models.CharField(default='000000', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verifyemail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verifyemail',
            name='expires_at',
            field=models.DateTimeField(default=accounts.models.default_expires_at),
        ),
    ]
