# Generated by Django 4.2.17 on 2025-02-09 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='emotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emotion', to='notes.emotions'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='location_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='location_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='tag_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_context', to='notes.contexts'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='tag_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_season', to='notes.seasons'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='tag_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_time', to='notes.times'),
        ),
        migrations.AlterField(
            model_name='plinotes',
            name='note_memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plis',
            name='tag_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pli_tag_context', to='notes.contexts'),
        ),
        migrations.AlterField(
            model_name='plis',
            name='tag_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pli_tag_season', to='notes.seasons'),
        ),
        migrations.AlterField(
            model_name='plis',
            name='tag_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pli_tag_time', to='notes.times'),
        ),
    ]
