# Generated by Django 4.2.17 on 2025-02-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_notes_emotion_alter_notes_location_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='album_art',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
