# Generated by Django 4.2.17 on 2025-02-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_notes_album_art'),
        ('notes', '0003_alter_notes_album_art_remove_notes_tag_context_and_more'),
    ]

    operations = [
    ]
