# Generated by Django 4.2.17 on 2025-02-25 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notes", "0005_alter_notes_emotion"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="댓글 내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성 날짜"),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        related_name="liked_note_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="좋아요",
                    ),
                ),
            ],
            options={
                "verbose_name": "노트 댓글",
                "verbose_name_plural": "노트 댓글들",
                "db_table": "notes_comments",
            },
        ),
        migrations.CreateModel(
            name="PliComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="댓글 내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성 날짜"),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        related_name="liked_pli_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="좋아요",
                    ),
                ),
            ],
            options={
                "verbose_name": "플리 댓글",
                "verbose_name_plural": "플리 댓글들",
                "db_table": "plis_comments",
            },
        ),
        migrations.RenameField(
            model_name="plis",
            old_name="archive_count",
            new_name="scrap_count",
        ),
        migrations.RemoveField(
            model_name="notes",
            name="archive_count",
        ),
        migrations.CreateModel(
            name="PliReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="대댓글 내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성 날짜"),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="notes.plicomment",
                        verbose_name="부모 댓글",
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        related_name="liked_pli_replies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="좋아요",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pli_replies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="대댓글 작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "플리 대댓글",
                "verbose_name_plural": "플리 대댓글들",
                "db_table": "plis_replies",
            },
        ),
        migrations.AddField(
            model_name="plicomment",
            name="pli",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="notes.plis",
                verbose_name="대상 플리",
            ),
        ),
        migrations.AddField(
            model_name="plicomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pli_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="댓글 작성자",
            ),
        ),
        migrations.CreateModel(
            name="NoteReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="대댓글 내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성 날짜"),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="notes.notecomment",
                        verbose_name="부모 댓글",
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        related_name="liked_note_replies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="좋아요",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_replies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="대댓글 작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "노트 대댓글",
                "verbose_name_plural": "노트 대댓글들",
                "db_table": "notes_replies",
            },
        ),
        migrations.CreateModel(
            name="NoteEmotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="감정을 남긴 날짜"),
                ),
                (
                    "emotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notes.emotions",
                        verbose_name="감정",
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notes.notes",
                        verbose_name="노트",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "노트 감정",
                "verbose_name_plural": "노트 감정들",
                "db_table": "note_emotions",
            },
        ),
        migrations.AddField(
            model_name="notecomment",
            name="note",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="notes.notes",
                verbose_name="대상 노트",
            ),
        ),
        migrations.AddField(
            model_name="notecomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="note_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="댓글 작성자",
            ),
        ),
    ]
