# Generated by Django 4.2.17 on 2025-03-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0006_notecomment_plicomment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notereply",
            name="mention",
            field=models.CharField(
                blank=True, default="", max_length=50, null=True, verbose_name="멘션 닉네임"
            ),
        ),
        migrations.AddField(
            model_name="plireply",
            name="mention",
            field=models.CharField(
                blank=True, default="", max_length=50, null=True, verbose_name="멘션 닉네임"
            ),
        ),
    ]
