# Generated by Django 4.2.17 on 2025-02-28 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_notes_emotion_alter_notes_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='emotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_emotion', to='notes.emotions'),
        ),
    ]
