# Generated by Django 4.2.17 on 2025-06-30 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notes", "0007_notereply_mention_plireply_mention"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField(verbose_name="댓글/대댓글 내용")),
                ("reason", models.TextField(verbose_name="신고 사유")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("note comment", "note comment"),
                            ("note reply", "note reply"),
                            ("playlist comment", "playlist comment"),
                            ("playlist reply", "playlist reply"),
                        ],
                        default="note comment",
                        max_length=20,
                    ),
                ),
                ("content_id", models.IntegerField(default=0)),
                (
                    "issue_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="위험 유저",
                    ),
                ),
                (
                    "report_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="신고 유저",
                    ),
                ),
            ],
        ),
    ]
