# Generated by Django 4.2.17 on 2025-02-28 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_notecomment_plicomment_and_more'),
        ('notes', '0007_alter_notes_emotion'),
    ]

    operations = [
    ]
