# Generated by Django 4.2.17 on 2025-07-19 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_commentreport'),
        ('notes', '0008_merge_20250228_1406'),
    ]

    operations = [
    ]
