# Generated by Django 4.2.17 on 2025-07-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_commentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='tag_context',
            field=models.ManyToManyField(blank=True, related_name='tag_context', to='notes.contexts'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='tag_season',
            field=models.ManyToManyField(blank=True, related_name='tag_season', to='notes.seasons'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='tag_time',
            field=models.ManyToManyField(blank=True, related_name='tag_time', to='notes.times'),
        ),
    ]
