# Generated by Django 4.2.17 on 2025-07-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_alter_notes_tag_context_alter_notes_tag_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plis',
            name='tag_context',
            field=models.ManyToManyField(blank=True, related_name='pli_tag_context', to='notes.contexts'),
        ),
        migrations.AlterField(
            model_name='plis',
            name='tag_season',
            field=models.ManyToManyField(blank=True, related_name='pli_tag_season', to='notes.seasons'),
        ),
        migrations.AlterField(
            model_name='plis',
            name='tag_time',
            field=models.ManyToManyField(blank=True, related_name='pli_tag_time', to='notes.times'),
        ),
    ]
