# Generated by Django 4.2.17 on 2025-07-20 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_merge_0008_commentreport_0008_merge_20250228_1406'),
        ('notes', '0010_alter_plis_tag_context_alter_plis_tag_season_and_more'),
    ]

    operations = [
    ]
