# Generated by Django 4.2.17 on 2025-07-27 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_userblock_pliblock_noteblock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pliblock',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pliblock',
            name='pli',
        ),
        migrations.RemoveField(
            model_name='pliblock',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userblock',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userblock',
            name='blocked_user',
        ),
        migrations.RemoveField(
            model_name='userblock',
            name='user',
        ),
        migrations.DeleteModel(
            name='NoteBlock',
        ),
        migrations.DeleteModel(
            name='PliBlock',
        ),
        migrations.DeleteModel(
            name='UserBlock',
        ),
    ]
