# Generated by Django 4.2.17 on 2025-02-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_notice_manager_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='manger_name',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='manger_profile',
        ),
        migrations.AddField(
            model_name='notice',
            name='manager_name',
            field=models.CharField(default='운영자', max_length=30),
        ),
        migrations.AddField(
            model_name='notice',
            name='manager_profile',
            field=models.IntegerField(default=0),
        ),
    ]
