# Generated by Django 4.2.17 on 2025-07-27 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noteblock',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pliblock',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userblock',
            options={'ordering': ['-created_at']},
        ),
    ]
