# Generated by Django 4.2.17 on 2025-08-07 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0013_alter_pliblock_unique_together_remove_pliblock_pli_and_more'),
        ('moderation', '0002_alter_noteblock_options_alter_pliblock_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PliReplyBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_pli_replies', to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='notes.plireply')),
            ],
            options={
                'db_table': 'pli_reply_blocks',
                'ordering': ['-created_at'],
                'unique_together': {('blocker', 'reply')},
            },
        ),
        migrations.CreateModel(
            name='PliCommentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_pli_comments', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='notes.plicomment')),
            ],
            options={
                'db_table': 'pli_comment_blocks',
                'ordering': ['-created_at'],
                'unique_together': {('blocker', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='NoteReplyBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_note_replies', to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='notes.notereply')),
            ],
            options={
                'db_table': 'note_reply_blocks',
                'ordering': ['-created_at'],
                'unique_together': {('blocker', 'reply')},
            },
        ),
        migrations.CreateModel(
            name='NoteCommentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_note_comments', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='notes.notecomment')),
            ],
            options={
                'db_table': 'note_comment_blocks',
                'ordering': ['-created_at'],
                'unique_together': {('blocker', 'comment')},
            },
        ),
    ]
