# Generated by Django 4.2.17 on 2025-07-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='noteword',
            constraint=models.UniqueConstraint(fields=('note', 'noun'), name='uniq_note_noun'),
        ),
    ]
