# Generated by Django 4.2.17 on 2025-02-25 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFollows",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="팔로우를 시작한 유저",
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="팔로우 당한 유저",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 팔로우 관계",
                "verbose_name_plural": "사용자 팔로우 관계",
                "db_table": "user_follows",
                "unique_together": {("follower", "following")},
            },
        ),
    ]
