# Generated by Django 4.2.17 on 2025-02-25 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="스크랩 리스트 이름")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 날짜"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="스크랩 유저",
                    ),
                ),
            ],
            options={
                "verbose_name": "스크랩 리스트",
                "verbose_name_plural": "스크랩 리스트들",
                "db_table": "scrap_lists",
            },
        ),
        migrations.CreateModel(
            name="ScrapPlaylists",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_id", models.PositiveIntegerField(verbose_name="플리 ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="스크랩 날짜"),
                ),
                (
                    "scrap_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collects.scraplist",
                        verbose_name="스크랩 리스트",
                    ),
                ),
            ],
            options={
                "verbose_name": "스크랩 플리",
                "verbose_name_plural": "스크랩 플리들",
                "db_table": "scrap_playlists",
            },
        ),
        migrations.CreateModel(
            name="ScrapNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_id", models.PositiveIntegerField(verbose_name="노트 ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="스크랩 날짜"),
                ),
                (
                    "scrap_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collects.scraplist",
                        verbose_name="스크랩 리스트",
                    ),
                ),
            ],
            options={
                "verbose_name": "스크랩 노트",
                "verbose_name_plural": "스크랩 노트들",
                "db_table": "scrap_notes",
            },
        ),
    ]
