# Generated by Django 4.2.17 on 2025-07-22 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('note', 'Note'), ('pli', 'Pli')], default='note', max_length=10, verbose_name='신고 대상 타입')),
                ('content_id', models.IntegerField(verbose_name='신고 대상 ID')),
                ('reason', models.TextField(verbose_name='신고 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_reports_received', to=settings.AUTH_USER_MODEL, verbose_name='위험 유저')),
                ('report_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_reports_made', to=settings.AUTH_USER_MODEL, verbose_name='신고 유저')),
            ],
            options={
                'db_table': 'post_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
