# Generated by Django 4.2.17 on 2025-07-22 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='신고 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reports_received', to=settings.AUTH_USER_MODEL, verbose_name='위험 유저')),
                ('report_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reports_made', to=settings.AUTH_USER_MODEL, verbose_name='신고 유저')),
            ],
            options={
                'db_table': 'user_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
