# Generated by Django 4.2.17 on 2025-08-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_spotify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotify',
            name='access_token',
            field=models.CharField(max_length=500),
        ),
    ]
